name: Create a comment on new issues

on:
  issues:
    types: [opened]   # We want this to run whenever we open an issue

jobs:
  comment-with-actions: # Name of the job
    runs-on: windows-latest
    steps:
      - name: Dump GitHub context
        run: |
          $json = '${{ toJSON(github.event) }}'
          $json | ConvertFrom-Json | ConvertTo-Json -Depth 100
        shell: pwsh

      - name: Create comment   
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

  comment-with-api:
    runs-on: windows-latest
    steps:
      - name: Install GitHub CLI
        run: choco install gh
        shell: cmd

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token $env:GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh

      - name: Create comment with API
        run: |
          gh api --method POST `
            -H "Accept: application/vnd.github+json" `
            -H "X-GitHub-Api-Version: 2022-11-28" `
            /repos/$env:GITHUB_REPOSITORY/issues/$env:ISSUE_NUMBER/comments `
            -f body="Me too"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        shell: pwsh
